Repository wecode-bootcamp-korea/36-1st-Team-Corner-backend, pull requests merged in 2022-08, with the labels that each got.

#1 [ADD] 초기 환경 세팅
  .env.sample
  .gitignore
  app.js
  package-lock.json
  package.json
  routes/index.js
Labels: 완료

#3 ADD: 공통사항적용
  models/dataSource.js
  routes/index.js
Labels: 완료

#2 [Add] 데이터 베이스 설계
  db/migrations/20220818073509_create_products_table.sql
  db/migrations/20220818073518_create_users_table.sql
  db/migrations/20220818073529_create_orders_table.sql
  db/migrations/20220818073533_create_carts_table.sql
  db/migrations/20220818073538_create_reviews_table.sql
Labels: 완료

#4 ADD: 회원가입, 로그인 기능추가
  .DS_Store
  controllers/authController.js
  db/migrations/20220818073518_create_users_table.sql
  models/authDao.js
  package-lock.json
  package.json
  routes/authRouter.js
  routes/index.js
  services/authService.js
  utils/validation.js
Labels: 완료

#5 [ADD] BULK INSERT 구현
  .gitignore
Labels: 완료

#6 [ADD] REVIEW POST, PATCH, DELETE / REVIEWS GET 구현
  controllers/reviewController.js
  middlewares/auth.js
  models/reviewDao.js
  routes/index.js
  routes/reviewRouter.js
  services/reviewService.js
  utils/commonAuth.js
  utils/validation.js
Labels: 완료

#7 ADD: 상품 정보 조회기능 추가
  .gitignore
  controllers/authController.js
  controllers/productController.js
  models/authDao.js
  models/productDao.js
  routes/index.js
  routes/productRouter.js
  routes/reviewRouter.js
  services/productService.js
Labels: 수정 요청

#8 [ADD] 제품 상세페이지 장바구니 담기, 조회 기능 구현
  controllers/cartController.js
  middlewares/auth.js
  models/authDao.js
  models/cartDao.js
  routes/cartRouter.js
  routes/index.js
  services/cartService.js
  utils/validation.js
Labels: 완료

#12 상품 조회 기능 보완(트랜잭션 이용하여 페이지네이션 할때 상품의 총개수도 보내기)
  controllers/productController.js
  models/productDao.js
  services/productService.js
Labels: 완료

#10 장바구니 정보 조회 기능 추가
  controllers/cartController.js
  models/cartDao.js
  routes/cartRouter.js
  routes/index.js
  services/cartService.js
Labels: 완료

#13 [ADD] 리뷰 전체 갯수 조회 기능 추가 구현
  controllers/reviewController.js
  models/reviewDao.js
  routes/commonRouter.js
  routes/index.js
  routes/reviewRouter.js
  services/reviewService.js
Labels: 완료

#11 장바구니 전체 삭제 기능과 하나씩 삭제하는 기능
  controllers/cartController.js
  controllers/productController.js
  models/cartDao.js
  routes/cartRouter.js
  services/cartService.js
Labels: 완료

#16 [ADD] REVIEWS 마이리뷰 pagination
  controllers/reviewController.js
  models/reviewDao.js
  services/reviewService.js
Labels: 완료

#15 (마지막!!!!) 장바구니 수량 변경 기능 반영
  controllers/cartController.js
  models/cartDao.js
  routes/cartRouter.js
  services/cartService.js
Labels: 멘토 리뷰 요청
